In [ ]:
#Script to create a random values Rectangular Matrix.

# __init__.py

import numpy as np

array = np.random.randint(50, size=(10, 10))

print("Next is displayed the random rectangular Matrix:\n")
print(array)

print("\n\n The rank of the Matrix array is:\n")
print(np.linalg.matrix_rank(array))


try:
    detArray=np.linalg.det(array)
    print(detArray)
except Exception as err:
    print("\n\n Oops!  It was not able to calculate the matrix determinant, it is not a square matrix")


# Calculating the inverse of the matrix
invArray=np.linalg.inv(array)
print(invArray)


Next is displayed the random rectangular Matrix:

[[46  9 44 32  7 45 27 20 48  3]
 [43 18 46 24 37 46 39 35 15 24]
 [35 34 27 30 26  9 21 21 32 12]
 [ 2 30 38  2  5 45 18 24 46 38]
 [25 25 17 48  6 11 38  7 25 46]
 [33 36  4 46  2 45 43 37 13 41]
 [27 22  7 47 12 15 39 26 27 19]
 [ 5  1  6 44 16  1 38  8 46  3]
 [35 38 38  8 26 23  4 13 32 45]
 [34 35 12  9 20 22  4 43 48 23]]


 The rank of the Matrix array is:

10
160175331829676.8
[[ 0.00331681  0.06467082  0.19336674 -0.05921782  0.23826506  0.1419533
  -0.62016184  0.09853444 -0.23046701  0.14982761]
 [-0.01159793  0.01484702  0.14807852 -0.01233504  0.09743983  0.09798519
  -0.33196975  0.05600649 -0.11575685  0.05300406]
 [ 0.01102328 -0.03841531 -0.13845206  0.04923735 -0.14703584 -0.14257394
   0.48734259 -0.11172531  0.15157807 -0.10682014]
 [ 0.02225876 -0.1306665  -0.3837681   0.07298831 -0.44337515 -0.26849084
   1.19235215 -0.19984929  0.45787248 -0.27631057]
 [-0.01111224 -0.0076496  -0.05421114 -0.00411906 -0.09038072 

In [1]:
import numpy as np

eigenvalues, eigenvectors = np.linalg.eig([[58,53,55],[53,71,74],[55,74,86]])
print("eigenvalues:",eigenvalues)
print("eigenvectors:\n",eigenvectors)

eigenvalues: [195.32763639  15.94410775   3.72825586]
eigenvectors:
 [[ 0.48595341  0.859551    0.1581814 ]
 [ 0.59060595 -0.18955538 -0.78438088]
 [ 0.64423124 -0.47459544  0.59977103]]
